@startuml

header CRenderDevice::on_idle()
footer xrEngine

start

    partition "Loading events" {
        if (has events?) then (yes)
            :App->LoadDraw();
            stop
        endif
    }

    :FrameMove;

    :Precache Frame;

    :Projections;

    fork
        partition "Rendering" {
            :Begin;
            :<seqRender>;
            :End;
        }

    fork again
        partition "Secondary thread" {
            while (has parallel?)
                :<seqParallel>;
            endwhile
            :<seqFrameMT>;
        }
    end fork

stop

@enduml
