@startuml

header CRenderDevice::Create()
footer xrEngine
hide footbox

participant RenderDevice
box "Render"
    participant Render
    participant ResourceManager
    participant HW
    participant Backend
endbox

RenderDevice  -> Render: SetupGPU()
RenderDevice <-- Render

RenderDevice  -> Render: Create()
Render  -> HW: CreateDevice()
Render <-- HW
create ResourceManager
Render -> ResourceManager
RenderDevice <-- Render

RenderDevice -> RenderDevice: _SetupStates()
RenderDevice -> Render: SetupStates()
RenderDevice <-- Render

RenderDevice -> Render: OnDeviceCreate()
Render -> Backend: OnDeviceCreate()
note over Backend: quad IB\n VB\n IB
Render <-- Backend

Render  -> ResourceManager: OnDeviceCreate()
note over ResourceManager: process shaders.xr
Render <-- ResourceManager

Render -> Render: create()
note over Render: alloc RenderTarget\n ModelPool\n LightManager
RenderDevice <-- Render

@enduml
