@startuml

class CHW {
	.. Device management ..
	+CreateDevice()
	+DestroyDevice()
	+Reset()
	.. Events ..
	+OnAppActivate()
	+OnAppDeactivate()

	-- Public data --
	+Caps
	+pDevice
	+pBaseRT
	+pBaseZB
	+DevPP
	+stats_manager
}

class CHWCaps {

}

CHW "1" *-- CHWCaps : contains

@enduml